name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
      -
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven and Build a jar package
        run: mvn -B package --file pom.xml

      - name: debug
        run: sudo apt-get update && sudo apt-get install tree -y && pwd && ls -al && ls -al target && tree && exit 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Find Shell
        id: find
        run: find . -name '*.pkr.hcl' -type f

      - name: Build AMI
        run: |
          packer init packer
          packer fmt packer
          packer validate packer
          packer build packer

#          packer init /packer
#          packer fmt /packer
#          packer validate /packer
#          packer build /packer

#          packer init ./packer
#          packer fmt ./packer
#          packer validate ./packer
#          packer build ./packer

#          packer init ../../../packer
#          packer fmt ../../../packer
#          packer validate ../../../packer
#          packer build ../../../packer
