name: Build and Deploy

on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Test Java Code and Build with Maven and Build a jar package
        run:
          mvn -B package -f ./pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp-0.0.1-SNAPSHOT
          path: ./target/webapp-0.0.1-SNAPSHOT.jar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Init,fmt and validate AMI
        run: |
          packer init ./packer
          packer fmt ./packer
          packer validate ./packer
          packer build ./packer

      - name: Get AMI id and Write into a json file
        run: |
          echo "{\"ImageId\": \"$(jq -r '.builds[0].artifact_id|split(":")[1]' ./manifest.json)\"}" >> launch-template-data.json

      - name: Create launch template version
        run: |
          aws ec2 create-launch-template-version --launch-template-name webapp-lt --launch-template-data file://launch-template-data.json --source-version 1

      - name: Update autoscaling group launch template
        run: |
          lsv=$(aws ec2 describe-launch-template-versions --launch-template-name webapp-lt --query 'LaunchTemplateVersions[0].VersionNumber')
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name csye6225-asg --launch-template "{\"LaunchTemplateName\":\"webapp-lt\",\"Version\":\"${lsv}\"}"

      - name: Refresh autoscaling group
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name csye6225-asg