name: Build and Deploy

on:
  pull_request:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Find Jar
        run: find . -name '*.jar' -type f

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp-0.0.1-SNAPSHOT
          path: ./webapp/target/webapp-0.0.1-SNAPSHOT.jar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Unit test, Build with Maven and Build a jar package
        run:
          mvn -B package -f ./pom.xml

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Find Shell
        run: find . -name '*.pkr.hcl' -type f

      - name: Init,fmt and validate Packer files
        run: |
          packer init packer
          packer fmt packer
          packer validate packer